# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0050_remove_mcq_question_mcq_answer2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='mcq_answer',
            field=models.CharField(default='no answer provided', max_length=200),
            preserve_default=False,
        ),
    ]
