# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0051_auto_20160608_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='choice_a',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='choice_b',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='choice_c',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mcq_question',
            name='choice_d',
            field=models.CharField(default='blank', max_length=200),
            preserve_default=False,
        ),
    ]
