# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0052_auto_20160608_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq_question',
            name='tag_content',
        ),
        migrations.RemoveField(
            model_name='mcq_question',
            name='tag_inconsistent',
        ),
        migrations.RemoveField(
            model_name='mcq_question',
            name='tag_sub_topic',
        ),
        migrations.RemoveField(
            model_name='mcq_question',
            name='tag_topic',
        ),
    ]
