# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa1', '0053_auto_20160608_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_set',
            name='mcq_question',
        ),
        migrations.AddField(
            model_name='mcq_question',
            name='question_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qa1.Question_Set'),
            preserve_default=False,
        ),
    ]
